name = "BetterFuelBarrels"; // name
picture = "./logo.edds"; // picture in expanded description
logoSmall = "./logo.edds"; // icon next to mod name when description is not expanded
logo = "./logo.edds"; // logo below game menu
logoOver = "./logo.edds"; // on mouse hover over logo
tooltip = "use barrels for fuel!"; // tool tip on mouse hover
overview = "Some mod overview"; // overview
action = "https://github.com/ChaosRifle"; // link
author = "ChaosRifle"; // author
version = "0.1"; // ver