name = "BetterFuelBarrels"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "use barrels for fuel!"; // tool tip on mouse hover
overview = "Some mod overview"; // overview
action = "https://github.com/ChaosRifle"; // link
author = "ChaosRifle"; // author
version = "0.1"; // version